#+TITLE: Exam DevOps Introduction Course
#+AUTHOR: Kyonax - Cristian Moreno

* Table Of Contents :toc:
- [[#questions-1014][Questions]]

* Questions [10/14]
- [ ] Que fase o etapa no corresponde al ciclo de vida segun DevOps?
  - NOT / Fase de Release
- [ ] Con que intencion nacio la cultura DevOps?
  - NOT / Nace con la mira de hacer que se gaste menos recursos y dinero en las empresas.
- [X] Si tienes un sitio web, donde ayudaria el especialista DevOps?
  - CORRECT / Todas las opciones son correctas
- [X] Los Servicios de una empresa afectan a todos los equipos de desarrollo pero, Como afecta a un especialista DevOps?
  - CORRECT / El especialista DevOps puede enfrentarse a mas herramientas, mas equipos a los cuales entender y ayudar.
- [X] Una empresa te contrata como especialista DevOps. Al escuchar a los equipos descubres que la aplicación esta teniendo muchos errores en ambientes productivo. ¿Qué puedes hacer para mejorar esto?
  - CORRECT / Agregar fases de testing automática y que evite que el código llegue a el ambiente productivo con errores.
- [X] Una empresa te contrata como especialista DevOps. Al escuchar a los equipos descubres que la aplicación tarda mucho en llegar a los ambientes productivos porque el proceso de mover el código es manual. ¿Qué haces para mejorar esto?
  - CORRECT / Para arreglar este problema, se crea un proceso de despliegue automático que toma el código de un sitio centralizado y lo coloca automáticamente en el ambiente productivo
- [ ] Una empresa te contrata como especialista DevOps y desea replicar su único ambiente en 3 mas dev, qa, pre-producción en la nube. ¿Qué estrategia usarias?
  - NOT / Usaría el CLI de la nube para crear cada uno de los objetos de la infra y repetiría este proceso por cada ambiente que necesita el cliente
- [X] Entras a una empresa como especialista DevOps y descubres que el código se copia desde la máquina del desarrollador a un servidor de producción. ¿Qué herramientas propones para mejorar esto?
  - CORRECT / Muestro las ventajas de GIT y propongo usar GitHub como repositorio de versiones para el código de la aplicación
- [X] En la empresa donde estás como especialista DevOps se han dado cuenta de que las credenciales de base de datos están muy desprotegidas y cualquiera de los integrantes del equipo puede entrar a los servidores de producción. ¿Cómo mejoras la seguridad en este punto?
  - CORRECT / Hago que las credenciales estén almacenadas en un servicio que las encripte y que nadie pueda obtenerlas a excepción de despliegue. También limitó a las personas que puedan acceder a esos recursos y hago políticas de cambio de contraseñas
- [X] Entras en una empresa que no sabe nada de DevOps, y tú objetivos es ir implantando la cultura DevOps poco a poco en la empresa. ¿Cuáles serían tus primeros retos?
  - CORRECT / El reto es convencer y hace entender que las mejoras que quieres proponer aportan valor a los procesos
- [X] Entras en una empresa que no sabe nada de DevOps, y tu objetivo es ir implantando la cultura DevOps poco a poco en la empresa. ¿Cuáles serían tus primeros pasos?
  - CORRECT / Estudias el estado de la empresa, ves que lenguaje y herramientas usan y planificas que puedes mejorar y luego propones y creas lo propuesto
- [ ] Entras a una empresa como especialista DevOps y te piden evaluar que tipo de herramientas de orquestación necesitan la empresa y te comenta lo siguiente: no puedes levantar ninguna virtual machine o instancias de EC2 en AWS porque no hay equipo que la mantenga. ¿Qué herramienta propondrías?
  - NOT / Usaría jenkins serverless dentro de AWS
- [X] Una empresa te contrata como especialista DevOps y te dice que su más grande problemas es pasar codigo a producción debido a que no tiene forma de probar el código antes de que llegue ahí. ¿Qué solución podrías proponer?
  - CORRECT / Todas las opciones son correctas
- [X] Estás en una empresa y tienen muchos problemas en cargar data debido a que es un proceso manual, pero hay muchos equipo que constantemente necesitan actualizar la base de datos. ¿Qué solución podrías proponer?
  - CORRECT / Propongo crear un pipeline de actualización de base de datos y cada equipo podrá usarlo para actualizar data cuando lo desee
